### ISSUE TITLE
Checklist for v1

### ISSUE THREAD

**Issue by NoMod-Programming** [NoMod-Programming/QSIL-Language#1]
For QSIL version 1:

- [ ] Finalized bytecode instruction set
- [ ] Object Oriented Design for primitive data types, such as strings or arrays. (e.g. Turn strings into a QSIL data type, and operate on those instead of python strings). 
- [ ] A compiler of some kind, even if it is not yet built in QSIL-Language. Just something to make sure that I don't have to write thousands of bytecodes to get a simple bootstrap running that would make it possible to have it compile itself at some point in the future
- [ ] Basic I/O and graphics primitives
- [ ] Sound primitives (playing a list of samples at a specified sampling rate)
- [ ] Documentation of the QSIL interpreter, and better documentation on the file-format and bytecode format
